# Site settings
title: Becca Larson and Tyler Reny
email: beccalarson@gmail.com	
description: > 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/beccalarson/beccalarson.github.io/" # the base hostname & protocol for your site
twitter_username: 	
github_username:  
encoding: UTF-8
# Build settings
markdown: kramdown

